"""Google CSE column

Revision ID: 1f662749ffde
Revises: df7e4f31d3da
Create Date: 2020-06-09 08:34:39.796348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f662749ffde'
down_revision = 'df7e4f31d3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('googlecse', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'googlecse')
    # ### end Alembic commands ###
