"""polyswarm + iocmatches

Revision ID: df7e4f31d3da
Revises: d9e128afb309
Create Date: 2020-06-07 21:24:23.054861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7e4f31d3da'
down_revision = 'd9e128afb309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iocmatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osintgoogle', sa.Text(), nullable=True),
    sa.Column('caseid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caseid'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cases', sa.Column('polyswarm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'polyswarm')
    op.drop_table('iocmatches')
    # ### end Alembic commands ###
